# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='Title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='Author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='books.Author'),
        ),
    ]
