# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20171019_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='NumberOfPages',
            new_name='Number_of_Pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='Author',
        ),
        migrations.AddField(
            model_name='book',
            name='Author_Name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
