# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 10:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0004_auto_20171019_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
