# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20171023_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Category',
            field=models.CharField(max_length=100),
        ),
    ]
