# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
